# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Linux
permissions:
  contents: read # access to check out code and install dependencies
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg libmagickwand-dev libmagickcore-dev build-essential pkg-config
          echo "Installing ImageMagick 7 from source..."
          wget https://github.com/ImageMagick/ImageMagick/archive/7.1.1-29.tar.gz
          tar xzf 7.1.1-29.tar.gz
          cd ImageMagick-7.1.1-29

          # Configure and build ImageMagick 7
          ./configure \
            --prefix=/usr/local \
            --enable-shared \
            --disable-static \
            --with-modules \
            --with-quantum-depth=16 \
            --with-hdri \
            --without-perl

          make -j$(nproc)
          sudo make install
          sudo ldconfig

          # Update pkg-config path
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"

          cd ..
      - uses: actions/checkout@v4
      - name: Build
        run: go build -x -v ./rocksonic.go
        env:
          CGO_ENABLED: 1
      - name: pwd
        run: pwd
      - name: list dir content
        run: ls -la
