# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Linux
permissions:
  contents: read # access to check out code and install dependencies
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg libmagickwand-dev libmagickcore-dev build-essential pkg-config
      - name: Verify installations
        run: |
          which ffmpeg
          ffmpeg -version
          which pkg-config
          pkg-config --modversion MagickWand MagickCore
          echo "PATH: $PATH"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
      - name: Verify FFmpeg installation
        run: |
          which ffmpeg
          ffmpeg -version
          echo "PATH: $PATH"
      - name: Build
        run: go build -x -v ./main.go
        env:
          CGO_ENABLED: 1
      - name: pwd
        run: pwd
      - name: list dir content
        run: ls -la
